### ISSUE TITLE
SkodaBoleroInfotainment example is missing bolero.h

### ISSUE THREAD

**Issue by Gombat** [alexzhornyak/SCXML-tutorial#21]
I am trying to run the SkodaBoleroInfotainment example in q Qt 5.15.2 qml environment and am missing the bolero.h in ScxmlBoleroExt.h

Where can I find it?

**Comment by alexzhornyak** [comment]
Hi, Qt will automatically generate it after hit 'Run qmake' button and then it will be located in exe target folder

![image](https://user-images.githubusercontent.com/18611095/178733544-cac806be-ec0b-403c-aae6-1041c972881a.png)
